### ISSUE TITLE
Trying to understand Cyclic Prefix Synchronization

### ISSUE THREAD

**Issue by jarodcs** [kit-cel/gr-lte#11]
Hi everyone, 

i would appreciate your help on the following question.
Here I am studying the steps for LTE synchronization (from gr-lte) and I am currently at the very first step: The Cyclic Prefix Synchronization to achieve symbol synchronization:

From what I could see, the cyclic prefix sync can be achieved by using the Gnuradio-Block: "CP-based Rough Symbol Sync Vec" as shown below (From the grc file "lte_top_block_siso").
![screenshot from 2017-04-17 02-34-17](https://cloud.githubusercontent.com/assets/6204500/25082431/a9415af4-2305-11e7-924a-954323948410.png)

After doing a "locate rough_symbol_sync_cc" command on my terminal, I found the following files: 
1) gr-lte/grc/lte_rough_symbol_sync_cc.xml         
2) gr-lte/include/lte/rough_symbol_sync_cc.h       
3) gr-lte/lib/rough_symbol_sync_cc_impl.h           
4) gr-lte/lib/rough_symbol_sync_cc_impl.cc          

and after checking the source code of them I could see that File 1 "calls" for File 2, and File3 and FIle4 are the implementations of File 2, right?
Then, from what I can understand the **hole correlation operation & cyclic prefix calculation** happens on File 4 but I need some help understanding the following doubts please:

1. What is this sentence for:    gr::io_signature::make( 1, 1, sizeof(gr_complex)*vlen)
2. What does **fftwf_malloc** on d_cp0=(gr_complex*)fftwf_malloc(sizeof(gr_complex)*d_cpl0*d_vlen)
![screenshot from 2017-04-17 03-17-49](https://cloud.githubusercontent.com/assets/6204500/25083397/b2938662-230b-11e7-8c46-c1a7282df21c.png)
Image for question 1&2.

3. What does **rough_symbol_sync_cc_impl::forecast(int noutput_items,gr_vector_int &ninput_items_required)**
![screenshot from 2017-04-17 03-18-46](https://cloud.githubusercontent.com/assets/6204500/25083417/da5940b0-230b-11e7-9bdc-ad53d7065c8c.png)

4. What does             
memcpy(d_cp0,in+i*d_vlen          ,sizeof(gr_complex)*d_cpl*d_vlen);
memcpy(d_cp1,in+(i+d_fftl)*d_vlen ,sizeof(gr_complex)*d_cpl*d_vlen);
![screenshot from 2017-04-17 03-21-41](https://cloud.githubusercontent.com/assets/6204500/25083490/425316fa-230c-11e7-8ccd-9fb11a073c21.png)

5. I understand that here it happens the correlation:
rough_symbol_sync_cc_impl::corr(gr_complex *res, gr_complex *x, gr_complex *y, int len)
But can somebody point where the multiplication of the sequences happen?
![screenshot from 2017-04-17 03-22-13](https://cloud.githubusercontent.com/assets/6204500/25083494/4b007216-230c-11e7-9ff8-7a5fd63f05ae.png)

I would really appreciate your help on this under the promise to keep contributing on the understanding this great library. 

Cheers
jarodcs

**Comment by jdemel** [comment]
Hi!
Please start with the [GNU Radio Guided Tutorials](https://wiki.gnuradio.org/index.php/Guided_Tutorials).
This will answer your questions 1 and 3. Also, it explains the code structure. Why are there multiple files etc. How are these files structured...

Q2: fftwf_malloc is a function that returns a buffer which is aligned for use in SSE/AVX. Please read the FFTW Docs or alter the code such that it uses "volk_malloc" which essentially provides the same functionality but is better suited for use with GR since it is part of VOLK.

Q4: Please read the C++ STL [memcpy doc](http://en.cppreference.com/w/cpp/string/byte/memcpy).

Q5: Please get familiar with [VOLK](http://libvolk.org/). It provides the functionality for [SIMD](https://en.wikipedia.org/wiki/SIMD) optimized code.

**Comment by jarodcs** [comment]
Professor Demel, please I need your help on the follwing issue ... 
I am running the grc file "lte_top_block_siso" with an USRP Source instead of the File Source block. 
I have a USRP B210 (no GPSDO) and when using openlte (LTE_fdd_dl_scan) and also srsLte (pdsch_ue) at a known dl_earfcn of a local Telco I can get the correctly cell ID (I mean the number matches with my collegues info) on both. Also srsLTE shows my SINR around 11 - 12.

But when running the grc file in all possible manners (i.e. only throttle enabled // with Deinterleave - add - Head - Throttle enable // etc.) I get a different Cell ID (every time a different value) which leads me to think that maybe the input data from USRP to the "CP-base Rough Symbol Sync" block is not being properly passed ... or maybe is another thing (I dont think is poor signal given my SINR is around 12, also when running uhd_fft I can see the LTE band strong, 50dB above noise floor with B210 maximum gain).

So the question, is in your opinion what might be happening and what are your suggestions for testing if my setup is correct (although I can't figure out what else can I do). I was trying to compare the streams at the output of the USRP vs the streams at output of the CP-Based Rough SYmbol Sync Block ... but I failed on the attempet given that I dont know how to do that ... and maybe it is worthless.
I will appreciate your suggestions.

![screenshot from 2017-04-28 09-48-19](https://cloud.githubusercontent.com/assets/6204500/25533995/51752aae-2be7-11e7-9731-e9b90d26538d.png)

**Comment by jdemel** [comment]
Hi!

First, the Throttle block exists in order to keep the computational load on your machine in check in case you DO NOT RUN hardware. With a USRP Source, you use hardware. Remove the throttle block.

Next, the deinterleave and add blocks won't be necessary. 

You should check if 'O's are printed to the shell. This is an indicator for dropped samples. And this will make the whole flowgraph fail.
Please note, that gr-lte is usually not able to keep up with LTE sample rates. It is intended to make it easier to understand the LTE signal processing flowgraph.

The 'cell ID' is published by the LTE SSS Sync block. You may deactivate all blocks behind this one for test purposes.

**Comment by ceren58** [comment]
Hi @jdemel , 
I am using lte_top_block_siso.grc with an USRP and I have the problem you are just talking about. I receive some "O" wtih the message "ofdm_lte_remove_cp_cvc_0 OUT of sync!". I know it is because of the USRP's overflow but I don't know haw to solve it. I would be grateful if you have the solution :)

**Comment by jdemel** [comment]
Your PC can't process samples fast enough. Record a sample file (a couple of seconds) and use this in your flowgraph afterwards.

**Comment by ceren58** [comment]
thank you for your quick answer and your help. 
I recorded a sample file using the USRP and I don't have problems of overflow anymore but still the same message of "ofdm_lte_remove_cp_cvc_0 OUT of sync!". I may have something else wrong...

**Comment by jarodcs** [comment]
Hi guys!

Correct me if I am wrong, but it seems that those are samples that USRP
took but they are out of frame or in other words are not cyclic prefix sync
... and it seems to me that it removes the ofdm cyclic prefix and finds out
that is not sync ... That is my guessing, hope Prof. Demel can explain that
error a little bit more. So those errors are normal because at first the
system is not sync with the "listened eNB".

Thanks

2017-08-11 11:52 GMT+00:00 ceren58 <notifications@github.com>:

**Comment by jdemel** [comment]
Something goes wrong. There are many possible reasons. For example, the flowgraph expects samples at certain sample rates. These sample rates are not supported by all USRPs. Resampling is required. The SNR of your recording might be too low. Or you experienced overflows during the recording.
You need to analyse the error in more detail in order to tell why things do not work as expected.
Also, you need to describe your whole system setup in order to allow others to guess what the source of the error is.

**Comment by Keskebeu** [comment]
I have lte on a core i7 quadcore and overflow does not occur. But in my core i5 dual-core  it does overflow. You can work on  2g and 3g but not on lte. So a better processor would be good to have to experiment on lte.

**Comment by mingli001** [comment]
@jarodcs Hi,i meet the same question.did you solve it?could you help me ?thank you
